trigger:
- main  # Substitua pelo nome da sua branch
 
pool:
  vmImage: 'ubuntu-latest'  # Escolha a imagem de máquina adequada
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Certifique-se de que a versão do NodeJS é compatível
 
- script: |
    npm install -g firebase-tools
  displayName: 'Instalar Firebase CLI'
 
- script: |
    npm install
  displayName: 'Instalar dependências'
 
- script: |
    firebase deploy --token $(FIREBASE_TOKEN)
  displayName: 'Deploy para Firebase Hosting'
  env:
    FIREBASE_TOKEN: $(FIREBASE_TOKEN)  # Use a variável de ambiente para o token